### ISSUE TITLE
Basic setup for React?

### ISSUE THREAD

**Issue by zaydek** [nedjulius/bun-plugin-stylex#4]
Hey there, thanks for making this. I have two questions: Is this intended to provide a way to build StyleX/React apps OR is this simply a way to make sure Bun doesn't error when it hits StyleX code, so that you can run commands like `bun test`?

If this is intended to make React apps, would it be possible to demonstrate a MVP use case for setting it up with React? I'm a little confused how it would work with an `index.html` file OR if you were imagining that React would be responsible for that.

Thanks!

**Comment by nedjulius** [comment]
hi @zaydek , this plugin can be used with any Bun project (React included) to compile StyleX styles. I [do have a very simple example app that uses Bun, React and StyleX](https://github.com/nedjulius/bun-plugin-stylex-example).

**Comment by zaydek** [comment]
Excellent -- thanks! Needed this. I'd recommend linking it anywhere in your readme. Will close this.
